---
- name: dummy
  debug:
    msg: "DUMMY HANDLER: SHOULDN'T BE CALLED!"

- name: restart etcd
  become: yes
  service:
    name: etcd
    daemon_reload: yes
    state: restarted
  listen: "restart kubernetes cluster"

- name: restart kubernetes api server
  become: yes
  service:
    name: kube-apiserver
    daemon_reload: yes
    state: restarted
  listen: "restart kubernetes cluster"

- name: restart kubernetes controller manager
  become: yes
  service:
    name: kube-controller-manager
    daemon_reload: yes
    state: restarted
  listen: "restart kubernetes cluster"

- name: restart kubernetes scheduler
  become: yes
  service:
    name: kube-scheduler
    daemon_reload: yes
    state: restarted
  listen: "restart kubernetes cluster"

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
  listen: "restart kubernetes cluster"
