---
- name: Kubernetes config directory
  become: yes
  file:
    path: /etc/kubernetes/config
    state: directory

# TODO: check already installed version
- name: Download kubernetes binaries
  become: yes
  get_url: 
    url: "{{ item }}"
    dest: /usr/local/bin/
    mode: "0755"
  loop:
    - "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64/kube-apiserver"
    - "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64/kube-controller-manager"
    - "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetes_version }}/bin/linux/amd64/kube-scheduler"

- name: Kubernetes var lib directory
  become: yes
  file:
    path: /var/lib/kubernetes/
    state: directory

