---
- name: Update and upgrade packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Clean apt cache
  command: apt-get clean
  become: yes
  changed_when: false
  args:
    warn: false
