---
# Do we really need embed-certs=true in these commands?
# Anwer: NO!, so we can just use a template instead.
- name: kubeconfig cluster config
  command: "kubectl config set-cluster {{ kubernates_cluster_name }} --certificate-authority=/home/{{ ansible_user }}/certs/ca.{{ certificate_authority_name }}.cer --embed-certs=true --server=https://{{ kubernetes_public_address }}:6443 --kubeconfig=/home/{{ ansible_user }}/{{ inventory_hostname }}.kubeconfig"

- name: kubeconfig crednetial config
  command: "kubectl config set-credentials system:node:{{ inventory_hostname }} --client-certificate=/home/{{ ansible_user }}/certs/system_node_{{ inventory_hostname }}.cer --client-key=/home/{{ ansible_user }}/certs/system_node_{{ inventory_hostname }}.key --embed-certs=true --kubeconfig=/home/{{ ansible_user }}/{{ inventory_hostname }}.kubeconfig"

- name: kbueconfig context config
  command: "kubectl config set-context default --cluster={{ kubernetes_cluster_name }} --user=system:node:{{ inventory_hostname }} --kubeconfig=/home/{{ ansible_user }}/{{ inventory_hostname }}.kubeconfig"

- name: kubeconfig use context
  command: "kubectl config use-context default --kubeconfig=/home/{{ ansible_user }}/{{ inventory_hostname }}.kubeconfig"
