---
- name: Making sure the kubernetes controller systems are setup
  hosts: kubernetes_controller
  tasks:

    - include_role:
        name: kubernetes/worker
      vars:
        ssh_keys:
          - "{{ lookup('file', '{{ \"~/.ssh/id_rsa.pub\" | expanduser }}') }}"
