---
- name: Making sure the kubernetes worker systems are setup
  hosts: kubernetes_worker
  tasks:

    - include_role:
        name: kubernetes/worker

- name: Making sure the kubernetes controller systems are setup
  hosts: kubernetes_controller
  tasks:

    - include_role:
        name: kubernetes/controller
